update rate-limiting test to use pre-compiled binary, test TSA in staging
Signed-off-by: Bob Callaway <bcallaway@google.com>

diff --git a/.github/workflows/rate-limiting.yml b/.github/workflows/rate-limiting.yml
--- a/.github/workflows/rate-limiting.yml
+++ b/.github/workflows/rate-limiting.yml
@@ -19,39 +19,48 @@ jobs:
     outputs:
       rekor_staging: ${{ steps.rekor_staging.outputs.rekor_staging }}
       fulcio_staging: ${{ steps.fulcio_staging.outputs.fulcio_staging }}
+      tsa_staging: ${{ steps.fulcio_staging.outputs.tsa_staging }}
       rekor_prod: ${{ steps.rekor_prod.outputs.rekor_prod }}
       fulcio_prod: ${{ steps.fulcio_prod.outputs.fulcio_prod }}
       summary: ${{ steps.msg.outputs.summary}}
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
-        with:
-          go-version-file: 'go.work'
-          check-latest: true
+      - name: Extract relevant binaries
+        run: |
+          docker pull ghcr.io/sigstore/sigstore-probers:latest
+          # the last argument in the next command is not used, it is required because the container doesn't have a default command
+          docker create --name binaries ghcr.io/sigstore/sigstore-probers /usr/local/bin/rate-limiting
+          docker cp binaries:/usr/local/bin/rate-limiting /usr/local/bin/
+
       - name: Rate Limit Rekor Staging
         id: rekor_staging
         continue-on-error: true
         run: |
           echo "rekor_staging=success" >> $GITHUB_OUTPUT
-          go run ./prober/rate-limiting.go --url https://rekor.sigstage.dev/api/v1/log || echo "rekor_staging=failed" >> $GITHUB_OUTPUT
+          rate-limiting --url https://rekor.sigstage.dev/api/v1/log || echo "rekor_staging=failed" >> $GITHUB_OUTPUT
       - name: Rate Limit Fulcio Staging
         id: fulcio_staging
         continue-on-error: true
         run: |
           echo "fulcio_staging=success" >> $GITHUB_OUTPUT
-          go run ./prober/rate-limiting.go --url https://fulcio.sigstage.dev/api/v1/rootCert || echo "fulcio_staging=failed" >> $GITHUB_OUTPUT
+          rate-limiting --url https://fulcio.sigstage.dev/api/v1/rootCert || echo "fulcio_staging=failed" >> $GITHUB_OUTPUT
+      - name: Rate Limit TSA Staging
+        id: tsa_staging
+        continue-on-error: true
+        run: |
+          echo "fulcio_staging=success" >> $GITHUB_OUTPUT
+          rate-limiting --url https://timestamp.sigstage.dev/api/v1/timestamp/certchain || echo "tsa_staging=failed" >> $GITHUB_OUTPUT
       - name: Rate Limit Rekor Prod
         id: rekor_prod
         continue-on-error: true
         run: |
           echo "rekor_prod=success" >> $GITHUB_OUTPUT
-          go run ./prober/rate-limiting.go --url https://rekor.sigstore.dev/api/v1/log || echo "rekor_prod=failed" >> $GITHUB_OUTPUT
+          rate-limiting --url https://rekor.sigstore.dev/api/v1/log || echo "rekor_prod=failed" >> $GITHUB_OUTPUT
       - name: Rate Limit Fulcio Prod
         id: fulcio_prod
         continue-on-error: true
         run: |
           echo "fulcio_prod=success" >> $GITHUB_OUTPUT
-          go run ./prober/rate-limiting.go --url https://fulcio.sigstore.dev/api/v1/rootCert || echo "fulcio_prod=failed" >> $GITHUB_OUTPUT
+          rate-limiting --url https://fulcio.sigstore.dev/api/v1/rootCert || echo "fulcio_prod=failed" >> $GITHUB_OUTPUT
       - name: Set messages
         id: msg
         run: |
@@ -78,7 +87,8 @@ jobs:
           "Rekor Staging": "${{ needs.rate-limiting.outputs.rekor_staging }}",
           "Rekor Prod": "${{ needs.rate-limiting.outputs.rekor_prod }}",
           "Fulcio Staging": "${{ needs.rate-limiting.outputs.fulcio_staging }}",
-          "Fulcio Prod": "${{ needs.rate-limiting.outputs.fulcio_prod }}"
+          "Fulcio Prod": "${{ needs.rate-limiting.outputs.fulcio_prod }}",
+          "Timestamp Staging": "${{ needs.rate-limiting.outputs.tsa_staging }}"
         }
       links: >
         [
